name: Daily Health Check

on:
  schedule:
    - cron: '*/20 * * * *' # Every day at 00:00 UTC
  workflow_dispatch:
   # Every 20 minutes

jobs:
  ping-health-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render health endpoint
        run: |
          curl --fail --silent --show-error https://resale-3us6.onrender.com/health
